<?php

/**
 * This is the model base class for the table "page_has_file".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PageHasFile".
 *
 * Columns in table "page_has_file" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $page_id
 * @property string $file_id
 *
 */
abstract class BasePageHasFile extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'page_has_file';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PageHasFile|PageHasFiles', $n);
	}

	public static function representingColumn() {
		return array(
			'page_id',
			'file_id',
		);
	}

	public function rules() {
		return array(
			array('page_id, file_id', 'required'),
			array('page_id, file_id', 'length', 'max'=>10),
			array('page_id, file_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'page_id' => null,
			'file_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('page_id', $this->page_id);
		$criteria->compare('file_id', $this->file_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}