<?php

/**
 * This is the model base class for the table "comment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comment".
 *
 * Columns in table "comment" available as properties of the model,
 * followed by relations of table "comment" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $page_id
 * @property string $comment
 * @property string $date_entered
 *
 * @property Page $page
 * @property User $user
 */
abstract class BaseComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comment|Comments', $n);
	}

	public static function representingColumn() {
		return 'comment';
	}

	public function rules() {
		return array(
			array('user_id, page_id, comment, date_entered', 'required'),
			array('user_id, page_id', 'length', 'max'=>10),
			array('id, user_id, page_id, comment, date_entered', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'page' => array(self::BELONGS_TO, 'Page', 'page_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'page_id' => null,
			'comment' => Yii::t('app', 'Comment'),
			'date_entered' => Yii::t('app', 'Date Entered'),
			'page' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('page_id', $this->page_id);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('date_entered', $this->date_entered, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}